// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_it-IT_2/project',
  'prefix': '',
  'method': 'hmm',
  'cacheToDisk': false,
  'lang': 'it-IT',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_it-IT_2/compile_hmm_22050_ph_lsp_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '1808a35af7480b64cff4f1b67e568275',
      'size': 9381,
    },
    {
      'path': '/voice_data_hmm_it-IT_2/engine_hmm_22050_ap-embedded_lsp.cfg',
      'url': '',
      'md5sum': '020c3128e7d289c7a4f153178d1be5dd',
      'size': 4766,
    },
    {
      'path': '/voice_data_hmm_it-IT_2/g2p_m3_syls0_stress0_it-IT.fst',
      'url': '',
      'md5sum': '73818b91e7c1e42ba2db67985c63e4a8',
      'size': 193783,
    },
    {
      'path': '/voice_data_hmm_it-IT_2/hmm_voice_it_it_kda_medium_22050_ph_lsp_swop_ap_msd_bin_8bit.voice',
      'url': '',
      'md5sum': '829dbd625f8f7904f0536dbf2ea33481',
      'size': 228158,
    },
    {
      'path': '/voice_data_hmm_it-IT_2/compressed_lexicon_it_it.blex',
      'url': '',
      'md5sum': '7a28d7bd77bb16f8fd02c5245ecb4cc8',
      'size': 3562392,
    },
    {
      'path': '/voice_data_hmm_it-IT_2/textnorm_kestrel.cfg',
      'url': '',
      'md5sum': '97427f37e374112ac84c311c866c33b9',
      'size': 564,
    },
    {
      'path': '/voice_data_hmm_it-IT_2/phonology.cfg',
      'url': '',
      'md5sum': '60ee02bb1acb35c2d938d8e1b7aa7180',
      'size': 7988,
    },
    {
      'path': '/voice_data_hmm_it-IT_2/phonology.pb',
      'url': '',
      'md5sum': '739e58a91814b62f403713207c9ec82f',
      'size': 2718,
    },
    {
      'path': '/voice_data_hmm_it-IT_2/resolve_homographs_simple_it.pb',
      'url': '',
      'md5sum': '762dd4e8613d9fa6affefcb6b43420b8',
      'size': 14209,
    },
    {
      'path': '/voice_data_hmm_it-IT_2/rewrite_android.far',
      'url': '',
      'md5sum': '578bc8442f09c457e3c1a711efa0e5da',
      'size': 154062,
    },
    {
      'path': '/voice_data_hmm_it-IT_2/roman_numeral_contexts.pb',
      'url': '',
      'md5sum': '4a0a187e9d8e04264a523b69ee584445',
      'size': 1325,
    },
    {
      'path': '/voice_data_hmm_it-IT_2/roman_numeral_android.far',
      'url': '',
      'md5sum': 'ccdeea212487c83df8774e07aeba7189',
      'size': 2766,
    },
    {
      'path': '/voice_data_hmm_it-IT_2/textnorm_params.pb',
      'url': '',
      'md5sum': 'df910993930ecb7cb747fb829cdabfce',
      'size': 8,
    },
    {
      'path': '/voice_data_hmm_it-IT_2/tokenize_and_classify_android.far',
      'url': '',
      'md5sum': '8158019c2901f5934e7ba0978f6253d5',
      'size': 948621,
    },
    {
      'path': '/voice_data_hmm_it-IT_2/verbalize_android.far',
      'url': '',
      'md5sum': 'e4c0ccb4961761acaf5760353ea7453e',
      'size': 1530017,
    },
    {
      'path': '/voice_data_hmm_it-IT_2/project',
      'url': '',
      'md5sum': 'f2660d4e14947545f862d98c8de9d0a8',
      'size': 1656,
    },
  ],
});
