// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_fr-FR_2/project',
  'prefix': '',
  'method': 'hmm',
  'cacheToDisk': false,
  'lang': 'fr-FR',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_fr-FR_2/compile_hmm_22050_ph_lsp_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '1808a35af7480b64cff4f1b67e568275',
      'size': 9381,
    },
    {
      'path': '/voice_data_hmm_fr-FR_2/engine_hmm_22050_ap-embedded_lsp.cfg',
      'url': '',
      'md5sum': '020c3128e7d289c7a4f153178d1be5dd',
      'size': 4766,
    },
    {
      'path': '/voice_data_hmm_fr-FR_2/g2p_m3_syls0_stress0_fr-FR.fst',
      'url': '',
      'md5sum': '4ab14f4da9d7dc7b0cd07dbc250b7673',
      'size': 476957,
    },
    {
      'path': '/voice_data_hmm_fr-FR_2/hmm_voice_fr_fr_vlf_medium_22050_ph_lsp_swop_ap_msd_bin_8bit.voice',
      'url': '',
      'md5sum': 'af7a1c62b41672a0d25b462f286c3ed8',
      'size': 241002,
    },
    {
      'path': '/voice_data_hmm_fr-FR_2/compressed_lexicon_fr_fr.blex',
      'url': '',
      'md5sum': 'ba9f7cabcec99680586bd644e816e593',
      'size': 5524200,
    },
    {
      'path': '/voice_data_hmm_fr-FR_2/textnorm_kestrel.cfg',
      'url': '',
      'md5sum': '97427f37e374112ac84c311c866c33b9',
      'size': 564,
    },
    {
      'path': '/voice_data_hmm_fr-FR_2/phonology.cfg',
      'url': '',
      'md5sum': 'cf119204a3b44d715b48b2feb5ea9b1a',
      'size': 12595,
    },
    {
      'path': '/voice_data_hmm_fr-FR_2/phonology.pb',
      'url': '',
      'md5sum': '427b49a3fb546fdf704f2296b4c6786d',
      'size': 2313,
    },
    {
      'path': '/voice_data_hmm_fr-FR_2/resolve_homographs_simple_fr.pb',
      'url': '',
      'md5sum': '1c8b5034ebc822377ad613b736c89aab',
      'size': 81563,
    },
    {
      'path': '/voice_data_hmm_fr-FR_2/rewrite_android.far',
      'url': '',
      'md5sum': '64af0356110fb5999692b80243cafa68',
      'size': 70443,
    },
    {
      'path': '/voice_data_hmm_fr-FR_2/roman_numeral_contexts.pb',
      'url': '',
      'md5sum': 'd65f45ab2ad829da1bac6228ec71ac54',
      'size': 710,
    },
    {
      'path': '/voice_data_hmm_fr-FR_2/roman_numeral_android.far',
      'url': '',
      'md5sum': 'a42a42a0af580125ae37162c52ddd9b1',
      'size': 3655,
    },
    {
      'path': '/voice_data_hmm_fr-FR_2/textnorm_params.pb',
      'url': '',
      'md5sum': 'df910993930ecb7cb747fb829cdabfce',
      'size': 8,
    },
    {
      'path': '/voice_data_hmm_fr-FR_2/tokenize_and_classify_android.far',
      'url': '',
      'md5sum': 'd8a0f93f09dd2165febd54c074da9960',
      'size': 964415,
    },
    {
      'path': '/voice_data_hmm_fr-FR_2/verbalize_android.far',
      'url': '',
      'md5sum': 'd5ce573dc344fdc4b7cc7a72c593b753',
      'size': 547205,
    },
    {
      'path': '/voice_data_hmm_fr-FR_2/project',
      'url': '',
      'md5sum': 'ad32e82dfd381ba8f049f09f83f8d794',
      'size': 1663,
    },
  ],
});
