// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_de-DE/project',
  'prefix': '',
  'method': 'hmm',
  'cacheToDisk': false,
  'lang': 'de-DE',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_de-DE/compile_hmm_22050_ph_lsp_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '1808a35af7480b64cff4f1b67e568275',
      'size': 9381,
    },
    {
      'path': '/voice_data_hmm_de-DE/engine_hmm_22050_ap-embedded_lsp.cfg',
      'url': '',
      'md5sum': '037b59c977290d0b8d43c87b638e2d9e',
      'size': 4766,
    },
    {
      'path': '/voice_data_hmm_de-DE/g2p_m3_syls0_stress0_de-DE.fst',
      'url': '',
      'md5sum': '9052b38ed7ad2b7c849a3bd96fd3d5fd',
      'size': 302851,
    },
    {
      'path': '/voice_data_hmm_de-DE/hmm_voice_de_de_nfh_medium_22050_ph_lsp_swop_ap_msd_bin_8bit.voice',
      'url': '',
      'md5sum': '4a23783b5c6e9229b4874f4e5ac64ed8',
      'size': 278198,
    },
    {
      'path': '/voice_data_hmm_de-DE/compressed_lexicon_de_de.blex',
      'url': '',
      'md5sum': 'a05547966d8cd386fdd9bed2ad9dbb1e',
      'size': 1258896,
    },
    {
      'path': '/voice_data_hmm_de-DE/de_number_names.far',
      'url': '',
      'md5sum': '039c8656c61ab267020e1a8cfec49c89',
      'size': 1078501,
    },
    {
      'path': '/voice_data_hmm_de-DE/phonology.cfg',
      'url': '',
      'md5sum': '954625264617d1f26f7b7fc55943492a',
      'size': 9030,
    },
    {
      'path': '/voice_data_hmm_de-DE/phonology.pb',
      'url': '',
      'md5sum': '9ecbb65dfeee1e885383862354f665c7',
      'size': 2290,
    },
    {
      'path': '/voice_data_hmm_de-DE/textnorm_swift_de.cfg',
      'url': '',
      'md5sum': 'd74b3c0c6785949fa770749d5d5769ab',
      'size': 101307,
    },
    {
      'path': '/voice_data_hmm_de-DE/project',
      'url': '',
      'md5sum': '5b8dfe160420e0d5235f2888503b0a3d',
      'size': 1082,
    },
  ],
});
