// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_en-GB/project',
  'prefix': '',
  'method': 'hmm',
  'cacheToDisk': false,
  'lang': 'en-GB',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_en-GB/compile_hmm_22050_ph_lsp_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '1808a35af7480b64cff4f1b67e568275',
      'size': 9381,
    },
    {
      'path': '/voice_data_hmm_en-GB/engine_hmm_22050_ap-embedded_lsp.cfg',
      'url': '',
      'md5sum': '037b59c977290d0b8d43c87b638e2d9e',
      'size': 4766,
    },
    {
      'path': '/voice_data_hmm_en-GB/g2p_m3_syls0_stress0_en-GB.fst',
      'url': '',
      'md5sum': 'ec2ea3afdcc11c2eee9d16cafe89aae7',
      'size': 243080,
    },
    {
      'path': '/voice_data_hmm_en-GB/hmm_voice_en_gb_fis_medium_22050_ph_lsp_swop_ap_msd_bin_8bit.voice',
      'url': '',
      'md5sum': 'ec490dbac07eb037b62d2636be36bce6',
      'size': 252974,
    },
    {
      'path': '/voice_data_hmm_en-GB/compressed_lexicon_en_gb.blex',
      'url': '',
      'md5sum': 'd53c2f25cf711a371f18a305a13a96c2',
      'size': 1348976,
    },
    {
      'path': '/voice_data_hmm_en-GB/en_number_names.far',
      'url': '',
      'md5sum': 'f0c36f0d374262b42e1b90a178e43704',
      'size': 607284,
    },
    {
      'path': '/voice_data_hmm_en-GB/phonology.cfg',
      'url': '',
      'md5sum': 'db3b8a7aebf93ee562f52ef88cf3aa6a',
      'size': 13565,
    },
    {
      'path': '/voice_data_hmm_en-GB/phonology.pb',
      'url': '',
      'md5sum': 'd4fa90d031e255da7082ed4662ff2ec1',
      'size': 2137,
    },
    {
      'path': '/voice_data_hmm_en-GB/textnorm_swift_en.cfg',
      'url': '',
      'md5sum': '9b5c744d875319de607beedc59f671ad',
      'size': 168178,
    },
    {
      'path': '/voice_data_hmm_en-GB/project',
      'url': '',
      'md5sum': 'd988b489909969a464d904ce7bdd3c4f',
      'size': 1082,
    },
  ],
});
