// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_en-US/project',
  'prefix': '',
  'method': 'hmm',
  'cacheToDisk': false,
  'lang': 'en-US',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_en-US/compile_hmm_22050_ph_lsp_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '1808a35af7480b64cff4f1b67e568275',
      'size': 9381,
    },
    {
      'path': '/voice_data_hmm_en-US/engine_hmm_22050_ap-embedded_lsp.cfg',
      'url': '',
      'md5sum': '037b59c977290d0b8d43c87b638e2d9e',
      'size': 4766,
    },
    {
      'path': '/voice_data_hmm_en-US/g2p_m3_syls0_stress0_en-US.fst',
      'url': '',
      'md5sum': '7b15090b15fe7cc4f21fea59992fcbae',
      'size': 401829,
    },
    {
      'path': '/voice_data_hmm_en-US/hmm_voice_en_us_sfg_medium_22050_ph_lsp_swop_ap_msd_bin_8bit.voice',
      'url': '',
      'md5sum': 'f869f2985c1342a95b784ba1ac21f578',
      'size': 241190,
    },
    {
      'path': '/voice_data_hmm_en-US/compressed_lexicon_en_us.blex',
      'url': '',
      'md5sum': '11a64073822e57ff3f17f0690b5ea7da',
      'size': 1908000,
    },
    {
      'path': '/voice_data_hmm_en-US/en_number_names.far',
      'url': '',
      'md5sum': 'f0c36f0d374262b42e1b90a178e43704',
      'size': 607284,
    },
    {
      'path': '/voice_data_hmm_en-US/phonology.cfg',
      'url': '',
      'md5sum': '7db0db9be20aba39d5fd8174c8143ccb',
      'size': 13581,
    },
    {
      'path': '/voice_data_hmm_en-US/phonology.pb',
      'url': '',
      'md5sum': '9024ab94936f876ba62f0407307a47e4',
      'size': 2137,
    },
    {
      'path': '/voice_data_hmm_en-US/textnorm_swift_en.cfg',
      'url': '',
      'md5sum': '9b5c744d875319de607beedc59f671ad',
      'size': 168178,
    },
    {
      'path': '/voice_data_hmm_en-US/project',
      'url': '',
      'md5sum': '7647f352fc6ed81ce4df680dd8614366',
      'size': 1082,
    },
  ],
});
