// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports Google voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'pipelineFile': '/voice_data_hmm_fr-FR/pipeline',
  'prefix': '',
  'voiceType': 'hmm',
  'cacheToDisk': false,
  'lang': 'fr-FR',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_fr-FR.zvoice',
      'url': '',
      'md5sum': '135be4ab307b5cf5058c33d5f3c69cc0',
      'size': 7020230,
    },
  ],
});
