// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_es-ES/project',
  'prefix': '',
  'method': 'hmm',
  'cacheToDisk': false,
  'lang': 'es-ES',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_es-ES/compile_hmm_22050_ph_lsp_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '1808a35af7480b64cff4f1b67e568275',
      'size': 9381,
    },
    {
      'path': '/voice_data_hmm_es-ES/engine_hmm_22050_ap-embedded_lsp.cfg',
      'url': '',
      'md5sum': '037b59c977290d0b8d43c87b638e2d9e',
      'size': 4766,
    },
    {
      'path': '/voice_data_hmm_es-ES/g2p_m3_syls0_stress0_es-ES.fst',
      'url': '',
      'md5sum': 'edef78ff6166dc0980853860d0b8364f',
      'size': 344074,
    },
    {
      'path': '/voice_data_hmm_es-ES/hmm_voice_es_es_ana_medium_22050_ph_lsp_swop_ap_msd_bin_8bit.voice',
      'url': '',
      'md5sum': 'dd71b3071403f6903228c9366948fd40',
      'size': 253830,
    },
    {
      'path': '/voice_data_hmm_es-ES/compressed_lexicon_es_es.blex',
      'url': '',
      'md5sum': 'c69f223260294a0ac0c7ba4ba3868020',
      'size': 1261540,
    },
    {
      'path': '/voice_data_hmm_es-ES/es_number_names.far',
      'url': '',
      'md5sum': 'd2aba5fab3ebeb6c363f8af9a70e6205',
      'size': 507619,
    },
    {
      'path': '/voice_data_hmm_es-ES/phonology.cfg',
      'url': '',
      'md5sum': '2eef0a20913268ca95396d05c3dbf206',
      'size': 6664,
    },
    {
      'path': '/voice_data_hmm_es-ES/phonology.pb',
      'url': '',
      'md5sum': 'aadb7145dd5f36bc78eb49b6d0ad6f7b',
      'size': 1513,
    },
    {
      'path': '/voice_data_hmm_es-ES/textnorm_swift_es.cfg',
      'url': '',
      'md5sum': 'd3b2fb3da09cb80ef1f6286383f8228e',
      'size': 38514,
    },
    {
      'path': '/voice_data_hmm_es-ES/project',
      'url': '',
      'md5sum': 'acca60f25996ca310fb6fa07f1197199',
      'size': 1082,
    },
  ],
});
