// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_de-DE_2/project',
  'prefix': '',
  'method': 'hmm',
  'cacheToDisk': false,
  'lang': 'de-DE',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_de-DE_2/compile_hmm_22050_ph_lsp_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '1808a35af7480b64cff4f1b67e568275',
      'size': 9381,
    },
    {
      'path': '/voice_data_hmm_de-DE_2/engine_hmm_22050_ap-embedded_lsp.cfg',
      'url': '',
      'md5sum': '020c3128e7d289c7a4f153178d1be5dd',
      'size': 4766,
    },
    {
      'path': '/voice_data_hmm_de-DE_2/g2p_m3_syls0_stress0_de-DE.fst',
      'url': '',
      'md5sum': '9052b38ed7ad2b7c849a3bd96fd3d5fd',
      'size': 302851,
    },
    {
      'path': '/voice_data_hmm_de-DE_2/hmm_voice_de_de_nfh_medium_22050_ph_lsp_swop_ap_msd_bin_8bit.voice',
      'url': '',
      'md5sum': '6b7989b39b22eb08eb128fd265d990dc',
      'size': 286750,
    },
    {
      'path': '/voice_data_hmm_de-DE_2/compressed_lexicon_de_de.blex',
      'url': '',
      'md5sum': 'b81bca0733870b649b7e8cddd7e575a2',
      'size': 2140516,
    },
    {
      'path': '/voice_data_hmm_de-DE_2/textnorm_kestrel.cfg',
      'url': '',
      'md5sum': '97427f37e374112ac84c311c866c33b9',
      'size': 564,
    },
    {
      'path': '/voice_data_hmm_de-DE_2/phonology.cfg',
      'url': '',
      'md5sum': '0aa2cbcf721f55c3c28ae7bbfbeadc6e',
      'size': 9722,
    },
    {
      'path': '/voice_data_hmm_de-DE_2/phonology.pb',
      'url': '',
      'md5sum': '4a8e117109684b0a44da67bc3c58c70d',
      'size': 2392,
    },
    {
      'path': '/voice_data_hmm_de-DE_2/resolve_homographs_simple_de.pb',
      'url': '',
      'md5sum': '99386a0b969f02bfaf9ef8cb7a5ad75c',
      'size': 1582,
    },
    {
      'path': '/voice_data_hmm_de-DE_2/rewrite_android.far',
      'url': '',
      'md5sum': '086792465a9c6c38c89c37f0c2296456',
      'size': 98600,
    },
    {
      'path': '/voice_data_hmm_de-DE_2/roman_numeral_contexts.pb',
      'url': '',
      'md5sum': '7cae8dd0c017ddb3a7361d08770c3371',
      'size': 8559,
    },
    {
      'path': '/voice_data_hmm_de-DE_2/roman_numeral_android.far',
      'url': '',
      'md5sum': 'dc4e79c96ad125280b459e4047de614c',
      'size': 1130,
    },
    {
      'path': '/voice_data_hmm_de-DE_2/textnorm_params.pb',
      'url': '',
      'md5sum': '715023773bd80c6f7ad15bb9aa226df9',
      'size': 16,
    },
    {
      'path': '/voice_data_hmm_de-DE_2/tokenize_and_classify_android.far',
      'url': '',
      'md5sum': 'a18fff0f4341108f5893f3ed12df7ee6',
      'size': 752051,
    },
    {
      'path': '/voice_data_hmm_de-DE_2/verbalize_android.far',
      'url': '',
      'md5sum': '9bfb169ac7e2d5bd2f0d9c5258ecb719',
      'size': 276209,
    },
    {
      'path': '/voice_data_hmm_de-DE_2/project',
      'url': '',
      'md5sum': '0f2e6d1317d0ba67987478f04f457dee',
      'size': 1656,
    },
  ],
});
