// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_es-ES_2/project',
  'prefix': '',
  'method': 'hmm',
  'cacheToDisk': false,
  'lang': 'es-ES',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_es-ES_2/compile_hmm_22050_ph_lsp_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '1808a35af7480b64cff4f1b67e568275',
      'size': 9381,
    },
    {
      'path': '/voice_data_hmm_es-ES_2/engine_hmm_22050_ap-embedded_lsp.cfg',
      'url': '',
      'md5sum': '020c3128e7d289c7a4f153178d1be5dd',
      'size': 4766,
    },
    {
      'path': '/voice_data_hmm_es-ES_2/g2p_m3_syls0_stress0_es-ES.fst',
      'url': '',
      'md5sum': '6a9bb2b2253a1c157cf120ddc06a453a',
      'size': 340362,
    },
    {
      'path': '/voice_data_hmm_es-ES_2/hmm_voice_es_es_ana_medium_22050_ph_lsp_swop_ap_msd_bin_8bit.voice',
      'url': '',
      'md5sum': '2a4871a264fe4543f2746d3b5b1ab675',
      'size': 256750,
    },
    {
      'path': '/voice_data_hmm_es-ES_2/compressed_lexicon_es_es.blex',
      'url': '',
      'md5sum': '956f0a8ae85bb219bf670fe56d6ed55c',
      'size': 2037096,
    },
    {
      'path': '/voice_data_hmm_es-ES_2/textnorm_kestrel.cfg',
      'url': '',
      'md5sum': '97427f37e374112ac84c311c866c33b9',
      'size': 564,
    },
    {
      'path': '/voice_data_hmm_es-ES_2/phonology.cfg',
      'url': '',
      'md5sum': 'accf70057cdd4b91b128c2e18235aa3c',
      'size': 7531,
    },
    {
      'path': '/voice_data_hmm_es-ES_2/phonology.pb',
      'url': '',
      'md5sum': 'c96125a832d65541bb9b79dd1d2ca933',
      'size': 1632,
    },
    {
      'path': '/voice_data_hmm_es-ES_2/resolve_homographs_simple_es.pb',
      'url': '',
      'md5sum': '8a92ac37cf9351dbe473268de8cdbf62',
      'size': 1203,
    },
    {
      'path': '/voice_data_hmm_es-ES_2/rewrite_android.far',
      'url': '',
      'md5sum': '4cdcb971c8db45ad84abd64231a3db0c',
      'size': 106124,
    },
    {
      'path': '/voice_data_hmm_es-ES_2/roman_numeral_contexts.pb',
      'url': '',
      'md5sum': '8d204c336c04a32b5525d39b80735e66',
      'size': 8996,
    },
    {
      'path': '/voice_data_hmm_es-ES_2/roman_numeral_android.far',
      'url': '',
      'md5sum': 'dc4e79c96ad125280b459e4047de614c',
      'size': 1130,
    },
    {
      'path': '/voice_data_hmm_es-ES_2/textnorm_params.pb',
      'url': '',
      'md5sum': 'a156eb74c8355332c380502b682ca39d',
      'size': 129,
    },
    {
      'path': '/voice_data_hmm_es-ES_2/tokenize_and_classify_android.far',
      'url': '',
      'md5sum': 'd4b7423f61ff7769919a8abbe93e3ff1',
      'size': 1109837,
    },
    {
      'path': '/voice_data_hmm_es-ES_2/verbalize_android.far',
      'url': '',
      'md5sum': '5a58d7243ab3cae66ae28a8028d05070',
      'size': 900699,
    },
    {
      'path': '/voice_data_hmm_es-ES_2/project',
      'url': '',
      'md5sum': 'a0221e18c3e1bf9a0464446dc61026ea',
      'size': 1656,
    },
  ],
});
