// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_fr-FR/project',
  'prefix': '',
  'method': 'hmm',
  'cacheToDisk': false,
  'lang': 'fr-FR',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_fr-FR/compile_hmm_22050_ph_lsp_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '1808a35af7480b64cff4f1b67e568275',
      'size': 9381,
    },
    {
      'path': '/voice_data_hmm_fr-FR/engine_hmm_22050_ap-embedded_lsp.cfg',
      'url': '',
      'md5sum': '037b59c977290d0b8d43c87b638e2d9e',
      'size': 4766,
    },
    {
      'path': '/voice_data_hmm_fr-FR/g2p_m3_syls0_stress0_fr-FR.fst',
      'url': '',
      'md5sum': '4ab14f4da9d7dc7b0cd07dbc250b7673',
      'size': 476957,
    },
    {
      'path': '/voice_data_hmm_fr-FR/hmm_voice_fr_fr_vlf_medium_22050_ph_lsp_swop_ap_msd_bin_8bit.voice',
      'url': '',
      'md5sum': 'a0effe90069c178eaeae519bf1a28bb6',
      'size': 262014,
    },
    {
      'path': '/voice_data_hmm_fr-FR/compressed_lexicon_fr_fr.blex',
      'url': '',
      'md5sum': 'f7383e5087d3e8808073be950c5c7f73',
      'size': 2377836,
    },
    {
      'path': '/voice_data_hmm_fr-FR/fr_number_names.far',
      'url': '',
      'md5sum': '2e8742de8d72cf817d171d4820bc5415',
      'size': 635851,
    },
    {
      'path': '/voice_data_hmm_fr-FR/phonology.cfg',
      'url': '',
      'md5sum': 'aaa1ad38deb58a52442c3257ae8166a5',
      'size': 12478,
    },
    {
      'path': '/voice_data_hmm_fr-FR/phonology.pb',
      'url': '',
      'md5sum': '238fc6ff6f0d99e7199b6995b2afdd8d',
      'size': 2345,
    },
    {
      'path': '/voice_data_hmm_fr-FR/textnorm_swift_fr.cfg',
      'url': '',
      'md5sum': 'b02f716095ce48b7d3e28e9766f7d4de',
      'size': 211895,
    },
    {
      'path': '/voice_data_hmm_fr-FR/project',
      'url': '',
      'md5sum': '89c1060b0df0cfd572d5078c313b2341',
      'size': 1089,
    },
  ],
});
