// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_en-US_2/project',
  'prefix': '',
  'method': 'hmm',
  'cacheToDisk': false,
  'lang': 'en-US',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_en-US_2/compile_hmm_22050_ph_lsp_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '1808a35af7480b64cff4f1b67e568275',
      'size': 9381,
    },
    {
      'path': '/voice_data_hmm_en-US_2/engine_hmm_22050_ap-embedded_lsp.cfg',
      'url': '',
      'md5sum': '020c3128e7d289c7a4f153178d1be5dd',
      'size': 4766,
    },
    {
      'path': '/voice_data_hmm_en-US_2/g2p_m3_syls0_stress0_en-US.fst',
      'url': '',
      'md5sum': '977d37a0a0946208d8aae828ba030a29',
      'size': 397265,
    },
    {
      'path': '/voice_data_hmm_en-US_2/hmm_voice_en_us_sfg_medium_22050_ph_lsp_swop_ap_msd_bin_8bit.voice',
      'url': '',
      'md5sum': 'b825d8f63a379317595cf3b2de90e7b0',
      'size': 243818,
    },
    {
      'path': '/voice_data_hmm_en-US_2/compressed_lexicon_en_us.blex',
      'url': '',
      'md5sum': '1deaa32772b59b92a482f88be5d5f4eb',
      'size': 1868524,
    },
    {
      'path': '/voice_data_hmm_en-US_2/textnorm_kestrel.cfg',
      'url': '',
      'md5sum': '97427f37e374112ac84c311c866c33b9',
      'size': 564,
    },
    {
      'path': '/voice_data_hmm_en-US_2/phonology.cfg',
      'url': '',
      'md5sum': 'dada80b6cb3d09dc5480756f2067c34f',
      'size': 12383,
    },
    {
      'path': '/voice_data_hmm_en-US_2/phonology.pb',
      'url': '',
      'md5sum': '2c5dba629f8c1b12f12d17f4ddd43186',
      'size': 2408,
    },
    {
      'path': '/voice_data_hmm_en-US_2/resolve_homographs_simple_us.pb',
      'url': '',
      'md5sum': 'f81138fb3f2ecb593c4ced1fb8dc4c95',
      'size': 42335,
    },
    {
      'path': '/voice_data_hmm_en-US_2/rewrite_android.far',
      'url': '',
      'md5sum': '4d9ee2adaf06943b409e786c270183bf',
      'size': 221720,
    },
    {
      'path': '/voice_data_hmm_en-US_2/roman_numeral_contexts.pb',
      'url': '',
      'md5sum': '6abaff02bd0b4ef77bdf3bdf13aafa36',
      'size': 8673,
    },
    {
      'path': '/voice_data_hmm_en-US_2/roman_numeral_android.far',
      'url': '',
      'md5sum': '8a7abc21cfd9cb207ce3133c0e4ede59',
      'size': 1282,
    },
    {
      'path': '/voice_data_hmm_en-US_2/textnorm_params.pb',
      'url': '',
      'md5sum': '13f4506658d3042eb5abdf41dc5801bc',
      'size': 78,
    },
    {
      'path': '/voice_data_hmm_en-US_2/tokenize_and_classify_android.far',
      'url': '',
      'md5sum': '1c7ba93da95b5fa07822ec00ea973fd7',
      'size': 4047191,
    },
    {
      'path': '/voice_data_hmm_en-US_2/verbalize_android.far',
      'url': '',
      'md5sum': 'c3ac38d1da5b5c0babf1468cad1a7b7b',
      'size': 341259,
    },
    {
      'path': '/voice_data_hmm_en-US_2/project',
      'url': '',
      'md5sum': 'c03be915b6269f7b9cb41e70ef5ad437',
      'size': 1675,
    },
  ],
});
