// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_pt-BR_2/project',
  'prefix': '',
  'method': 'hmm',
  'cacheToDisk': false,
  'lang': 'pt-BR',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_pt-BR_2/compile_hmm_22050_ph_lsp_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '1808a35af7480b64cff4f1b67e568275',
      'size': 9381,
    },
    {
      'path': '/voice_data_hmm_pt-BR_2/engine_hmm_22050_ap-embedded_lsp.cfg',
      'url': '',
      'md5sum': '020c3128e7d289c7a4f153178d1be5dd',
      'size': 4766,
    },
    {
      'path': '/voice_data_hmm_pt-BR_2/g2p_m3_syls0_stress0_pt-BR.fst',
      'url': '',
      'md5sum': '78c6fd06a822340bf90d83c2848c2b5a',
      'size': 191655,
    },
    {
      'path': '/voice_data_hmm_pt-BR_2/hmm_voice_pt_br_afs_medium_22050_ph_lsp_swop_ap_msd_bin_8bit.voice',
      'url': '',
      'md5sum': '44f5e7837c2675ce20904c1f0c6852a4',
      'size': 210578,
    },
    {
      'path': '/voice_data_hmm_pt-BR_2/compressed_lexicon_pt_br.blex',
      'url': '',
      'md5sum': '03b709044db8b625b5c691f7dc2838d3',
      'size': 1083512,
    },
    {
      'path': '/voice_data_hmm_pt-BR_2/textnorm_kestrel.cfg',
      'url': '',
      'md5sum': '97427f37e374112ac84c311c866c33b9',
      'size': 564,
    },
    {
      'path': '/voice_data_hmm_pt-BR_2/phonology.cfg',
      'url': '',
      'md5sum': '6f41207bcddfc0031e12db3099d4c737',
      'size': 8229,
    },
    {
      'path': '/voice_data_hmm_pt-BR_2/phonology.pb',
      'url': '',
      'md5sum': 'eeda6ab04c8c3ae1ebed1f97ed45c54b',
      'size': 1506,
    },
    {
      'path': '/voice_data_hmm_pt-BR_2/resolve_homographs_simple_br.pb',
      'url': '',
      'md5sum': '9d579474c7ba8b8fdbdc5baa0f4a168f',
      'size': 3392,
    },
    {
      'path': '/voice_data_hmm_pt-BR_2/rewrite_android.far',
      'url': '',
      'md5sum': 'ad9c6da1665db980f0496b572b07705d',
      'size': 150624,
    },
    {
      'path': '/voice_data_hmm_pt-BR_2/roman_numeral_contexts.pb',
      'url': '',
      'md5sum': '8db0983efce5afef634441a6258ff195',
      'size': 8567,
    },
    {
      'path': '/voice_data_hmm_pt-BR_2/roman_numeral_android.far',
      'url': '',
      'md5sum': 'dc4e79c96ad125280b459e4047de614c',
      'size': 1130,
    },
    {
      'path': '/voice_data_hmm_pt-BR_2/textnorm_params.pb',
      'url': '',
      'md5sum': 'df910993930ecb7cb747fb829cdabfce',
      'size': 8,
    },
    {
      'path': '/voice_data_hmm_pt-BR_2/tokenize_and_classify_android.far',
      'url': '',
      'md5sum': '2a6285b9263feb5497692ee891277a32',
      'size': 723627,
    },
    {
      'path': '/voice_data_hmm_pt-BR_2/verbalize_android.far',
      'url': '',
      'md5sum': '07b4a6c467832ba4e035ac67c4342b5f',
      'size': 671611,
    },
    {
      'path': '/voice_data_hmm_pt-BR_2/project',
      'url': '',
      'md5sum': '6a84a142a503a86129192568504cd5c4',
      'size': 1656,
    },
  ],
});
