// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_es-US_2/project',
  'prefix': '',
  'method': 'hmm',
  'cacheToDisk': false,
  'lang': 'es-US',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_es-US_2/compile_hmm_22050_ph_lsp_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '1808a35af7480b64cff4f1b67e568275',
      'size': 9381,
    },
    {
      'path': '/voice_data_hmm_es-US_2/engine_hmm_22050_ap-embedded_lsp.cfg',
      'url': '',
      'md5sum': '020c3128e7d289c7a4f153178d1be5dd',
      'size': 4766,
    },
    {
      'path': '/voice_data_hmm_es-US_2/g2p_m3_syls0_stress0_es-US.fst',
      'url': '',
      'md5sum': '8891bfc0ea5d48e9e4a72a15d00f3231',
      'size': 316021,
    },
    {
      'path': '/voice_data_hmm_es-US_2/hmm_voice_es_us_sfb_medium_22050_ph_lsp_swop_ap_msd_bin_8bit.voice',
      'url': '',
      'md5sum': '6cf127822c394e971e6b58ae2d188693',
      'size': 280862,
    },
    {
      'path': '/voice_data_hmm_es-US_2/compressed_lexicon_es_us.blex',
      'url': '',
      'md5sum': 'bf7af6d35d5540e5ad7c61586f2e1bb6',
      'size': 2876956,
    },
    {
      'path': '/voice_data_hmm_es-US_2/textnorm_kestrel.cfg',
      'url': '',
      'md5sum': '97427f37e374112ac84c311c866c33b9',
      'size': 564,
    },
    {
      'path': '/voice_data_hmm_es-US_2/phonology.cfg',
      'url': '',
      'md5sum': 'd534076e196fb228db98ad03c5b00e0c',
      'size': 9341,
    },
    {
      'path': '/voice_data_hmm_es-US_2/phonology.pb',
      'url': '',
      'md5sum': '40203c0960fe4807008669a5dc039190',
      'size': 1910,
    },
    {
      'path': '/voice_data_hmm_es-US_2/resolve_homographs_simple_us.pb',
      'url': '',
      'md5sum': 'cadab779462932fe683a41fa78276400',
      'size': 5178,
    },
    {
      'path': '/voice_data_hmm_es-US_2/rewrite_android.far',
      'url': '',
      'md5sum': '4cdcb971c8db45ad84abd64231a3db0c',
      'size': 106124,
    },
    {
      'path': '/voice_data_hmm_es-US_2/roman_numeral_contexts.pb',
      'url': '',
      'md5sum': '8d204c336c04a32b5525d39b80735e66',
      'size': 8996,
    },
    {
      'path': '/voice_data_hmm_es-US_2/roman_numeral_android.far',
      'url': '',
      'md5sum': 'dc4e79c96ad125280b459e4047de614c',
      'size': 1130,
    },
    {
      'path': '/voice_data_hmm_es-US_2/textnorm_params.pb',
      'url': '',
      'md5sum': '4b986d182444b50db93f57a5acf53f64',
      'size': 143,
    },
    {
      'path': '/voice_data_hmm_es-US_2/tokenize_and_classify_android.far',
      'url': '',
      'md5sum': 'd4b7423f61ff7769919a8abbe93e3ff1',
      'size': 1109837,
    },
    {
      'path': '/voice_data_hmm_es-US_2/verbalize_android.far',
      'url': '',
      'md5sum': '5a58d7243ab3cae66ae28a8028d05070',
      'size': 900699,
    },
    {
      'path': '/voice_data_hmm_es-US_2/project',
      'url': '',
      'md5sum': '9a9d1c81fe7052e358da2c4b55efaf20',
      'size': 1656,
    },
  ],
});
