// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_en-IN_2/project',
  'prefix': '',
  'method': 'hmm',
  'cacheToDisk': false,
  'lang': 'en-IN',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_en-IN_2/compile_hmm_22050_ph_lsp_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '1808a35af7480b64cff4f1b67e568275',
      'size': 9381,
    },
    {
      'path': '/voice_data_hmm_en-IN_2/engine_hmm_22050_ap-embedded_lsp.cfg',
      'url': '',
      'md5sum': '020c3128e7d289c7a4f153178d1be5dd',
      'size': 4766,
    },
    {
      'path': '/voice_data_hmm_en-IN_2/g2p_m3_syls0_stress0_en-IN.fst',
      'url': '',
      'md5sum': 'bd40958021c53dd5f37c50ff3fd65f97',
      'size': 438527,
    },
    {
      'path': '/voice_data_hmm_en-IN_2/hmm_voice_en_in_ahp_medium_22050_ph_lsp_swop_ap_msd_bin_8bit.voice',
      'url': '',
      'md5sum': 'd39374a5a158bb774bcd816d4e8e1380',
      'size': 238058,
    },
    {
      'path': '/voice_data_hmm_en-IN_2/compressed_lexicon_en_in.blex',
      'url': '',
      'md5sum': '408b5b245839d8c8724f5e000b940128',
      'size': 1514024,
    },
    {
      'path': '/voice_data_hmm_en-IN_2/textnorm_kestrel.cfg',
      'url': '',
      'md5sum': '97427f37e374112ac84c311c866c33b9',
      'size': 564,
    },
    {
      'path': '/voice_data_hmm_en-IN_2/phonology.cfg',
      'url': '',
      'md5sum': '069f0da6b2bae55c7e34c854cfa20359',
      'size': 13603,
    },
    {
      'path': '/voice_data_hmm_en-IN_2/phonology.pb',
      'url': '',
      'md5sum': '2225acc102bab37d5e1896050ea12cfb',
      'size': 2550,
    },
    {
      'path': '/voice_data_hmm_en-IN_2/resolve_homographs_simple_in.pb',
      'url': '',
      'md5sum': 'f81138fb3f2ecb593c4ced1fb8dc4c95',
      'size': 42335,
    },
    {
      'path': '/voice_data_hmm_en-IN_2/rewrite_android.far',
      'url': '',
      'md5sum': '4d9ee2adaf06943b409e786c270183bf',
      'size': 221720,
    },
    {
      'path': '/voice_data_hmm_en-IN_2/roman_numeral_contexts.pb',
      'url': '',
      'md5sum': '6abaff02bd0b4ef77bdf3bdf13aafa36',
      'size': 8673,
    },
    {
      'path': '/voice_data_hmm_en-IN_2/roman_numeral_android.far',
      'url': '',
      'md5sum': '8a7abc21cfd9cb207ce3133c0e4ede59',
      'size': 1282,
    },
    {
      'path': '/voice_data_hmm_en-IN_2/textnorm_params.pb',
      'url': '',
      'md5sum': 'ddb803e9f27e4b24254c20de39e1ab2f',
      'size': 77,
    },
    {
      'path': '/voice_data_hmm_en-IN_2/tokenize_and_classify_android.far',
      'url': '',
      'md5sum': '1c7ba93da95b5fa07822ec00ea973fd7',
      'size': 4047191,
    },
    {
      'path': '/voice_data_hmm_en-IN_2/verbalize_android.far',
      'url': '',
      'md5sum': 'c3ac38d1da5b5c0babf1468cad1a7b7b',
      'size': 341259,
    },
    {
      'path': '/voice_data_hmm_en-IN_2/project',
      'url': '',
      'md5sum': '61b5583eac9f0819cd71034a38114c71',
      'size': 1675,
    },
  ],
});
