// Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE
//
// This file is autogenerated! If you need to modify it, be sure to
// modify the script that exports patts voice data for use in Chrome.

// Initialize the voice array if it doesn't exist so that voice data files
// can be loaded in any order.

if (!window.voices) {
  window.voices = [];
}

// Add this voice to the global voice array.
window.voices.push({
  'projectFile': '/voice_data_hmm_it-IT/project',
  'prefix': '',
  'method': 'hmm',
  'cacheToDisk': false,
  'lang': 'it-IT',
  'gender': 'female',
  'removePaths': [],
  'files': [
    {
      'path': '/voice_data_hmm_it-IT/compile_hmm_22050_ph_lsp_swop_ap_msd.cfg',
      'url': '',
      'md5sum': '1808a35af7480b64cff4f1b67e568275',
      'size': 9381,
    },
    {
      'path': '/voice_data_hmm_it-IT/engine_hmm_22050_ap-embedded_lsp.cfg',
      'url': '',
      'md5sum': '037b59c977290d0b8d43c87b638e2d9e',
      'size': 4766,
    },
    {
      'path': '/voice_data_hmm_it-IT/g2p_m3_syls0_stress0_it-IT.fst',
      'url': '',
      'md5sum': '73818b91e7c1e42ba2db67985c63e4a8',
      'size': 193783,
    },
    {
      'path': '/voice_data_hmm_it-IT/hmm_voice_it_it_kda_medium_22050_ph_lsp_swop_ap_msd_bin_8bit.voice',
      'url': '',
      'md5sum': 'ec28f706bce8a69ded7d2c9c1ae1baa8',
      'size': 226562,
    },
    {
      'path': '/voice_data_hmm_it-IT/it_only.blex',
      'url': '',
      'md5sum': 'db1fcc88491ad84789298e13b807de42',
      'size': 2085788,
    },
    {
      'path': '/voice_data_hmm_it-IT/it_number_names.far',
      'url': '',
      'md5sum': '491e385a4a92a8995b514380c2b00be3',
      'size': 249493,
    },
    {
      'path': '/voice_data_hmm_it-IT/phonology.cfg',
      'url': '',
      'md5sum': '4a1c3f6870d9f419b140b0738eecb7d7',
      'size': 6545,
    },
    {
      'path': '/voice_data_hmm_it-IT/phonology.pb',
      'url': '',
      'md5sum': '4cfccb8b17145dd0e4ca4d2a6c537279',
      'size': 1696,
    },
    {
      'path': '/voice_data_hmm_it-IT/textnorm_swift_it.cfg',
      'url': '',
      'md5sum': '14065d2dc687e799915318ee786862cd',
      'size': 50824,
    },
    {
      'path': '/voice_data_hmm_it-IT/project',
      'url': '',
      'md5sum': '679351f7fa9b47b0422b0f5b8185a5ee',
      'size': 1065,
    },
  ],
});
